### ISSUE TITLE
Deleted events stay in OC

### ISSUE THREAD

**Issue by RaSKoR** [buzz/ics2owncloud.py#1]
Hi,

First, thanks for your tools because I can't use OC Calendar without remote calendars subscriptions.

However, the events which are deleted on the remote calendar stay presents into OC calendars. 

Did you think that you can fix it before the version 1.1 (planned for the 12/04 (DD/MM)) update of OC calendar app ? Perhaps it will be nice to delete all events before import then into OC.

Regards
R_K

**Comment by buzz** [comment]
Thanks for the feedback.

Will look into this.
