### ISSUE TITLE
ValueError: Found no components where exactly one is required: u''

### ISSUE THREAD

**Issue by renne** [buzz/ics2owncloud.py#14]
Hi, for two days I get the following error messages:

`
Traceback (most recent call last):
  File "./ics2owncloud.py", line 77, in <module>
    Config.get(key, 'ics_url'),
  File "./ics2owncloud.py", line 33, in do_import
    c = Calendar.from_ical(requests.get(ics_url).text)
  File "/usr/lib64/python2.7/site-packages/icalendar/cal.py", line 367, in from_ical
    '{st!r}'.format(**locals()))
ValueError: Found no components where exactly one is required: u''
`

What's going wrong?

**Comment by renne** [comment]
The Webcal-feed returns an empty page.

I suggest to add a human-readable error message for that case.

**Comment by buzz** [comment]
The error message is there and should be understandable:
`ValueError: Found no components where exactly one is required: u''`

But feel free to create a PR to make this more user-friendly.
