### ISSUE TITLE
THIS SCRIPT IS DEPRECATED.

### ISSUE THREAD

**Issue by liamjack** [buzz/ics2owncloud.py#20]
I disagree with the "THIS SCRIPT IS DEPRECATED." mention in the project's `README.md`, you can indeed now subscribe to an external ICS URL via the OwnCloud calendar and import it regularly, but one feature that is lacking is that this "imported calendar" is not available via CalDAV for syncing with other devices (Smartphone for example).

And this is precisely where your script comes in handy, since the ICS is imported into an existing calendar that can then be synced to other devices, which is exactly what I need :)

**Comment by buzz** [comment]
Good point! Thx
