### ISSUE TITLE
Pyhton3 support

### ISSUE THREAD

**Issue by buzz** [buzz/ics2owncloud.py#21]
This script should probably be converted to support Python3?

Anyone?

**Comment by canoine** [comment]
#23 seems to work (on my machine ^^). As I'm not a python specialist, I suppose this can be optimized.

**Comment by buzz** [comment]
Closed in d55fe0940566604ca49a596692603945618d124f, 452fb7d70e0239bafc53b62ba8e13a78eee7c990
