### ISSUE TITLE
SyntaxError: (unicode error) 'unicodeescape'

### ISSUE THREAD

**Issue by kriztan** [buzz/ics2owncloud.py#3]
Thanks for your script. I'm running this to sync a ms outlook calendar with owncloud 9 and I'm getting this error:
`File "ics2owncloud.py", line 46
    if r.status_code == 500 and 'Sabre\VObject\Recur\NoInstancesException' in r.text:
                                   ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 19-20: malformed \N character escape`

Any ideas?

**Comment by buzz** [comment]
Oh, thanks. This is a bug.

The unicode codec interprets `\N` as the start of a special escape sequence. The string must be escaped properly or even easier: we can mark it as raw by prefixing it with an r:

```
r'Sabre\VObject\Recur\NoInstancesException'
```

I don't reproduce the error so I can't test. Could you try if that works for you?

**Comment by kriztan** [comment]
Thanks for your help, now I'm getting another error:
`Traceback (most recent call last):
  File "ics2owncloud.py", line 5, in <module>
    import ConfigParser
ImportError: No module named 'ConfigParser'`

What is wrong? Do you use Python 2 or 3?

**Comment by buzz** [comment]
2.7

Should work know.

**Comment by kriztan** [comment]
Thanks, now I'm getting no response and no imported calendar entries. Is there a way to debug?

**Comment by buzz** [comment]
I never tried Outlook so I can't debug it myself without having the data.

But apparently the script didn't find any events in the Outlook export. It should be proper iCal format.
Check by downloading the file yourself and open it with a text editor.
