### ISSUE TITLE
caldav

### ISSUE THREAD

**Issue by stefanbesler** [buzz/ics2owncloud.py#4]
Hi!
In order for your script to work for me I hat to change the URL to owncloud

Before:
CALDAVURL = '%sremote.php/dav/calendars/%s/%s'

After:
CALDAVURL = '%sremote.php/caldav/calendars/%s/%s'

Thanks for your script! I used the same php script as you :-D

**Comment by stefanbesler** [comment]
I would fork it and submit it, but since it is only one line ... ;)
maybe you should make it configurable in the ini file

**Comment by buzz** [comment]
Could you create a pull request? Thx!

**Comment by Maxqia** [comment]
This project is for ownCloud 9, this is only a problem if you use ownCloud 8 :P
