### ISSUE TITLE
Selfsigned Certificate

### ISSUE THREAD

**Issue by ghost** [buzz/ics2owncloud.py#5]
Thanks for your script! 
I ran into problems, as my certificate is self-signed.
As I don't know how python stores certificates I simply inserted
the option verify=False for all requests. Perhaps you could integrate a config-option?
Best regards,
Thomas

**Comment by buzz** [comment]
I would recommend against using self-signed certificates for production. Certificates are verified for a good reason.

You can get free (as in free beer) certificates from [Let's Encrypt](https://letsencrypt.org/).

If you still want this feature you create a PR and don't forget to insert a fat warning and I'll consider to pull from that. ;)

**Comment by ghost** [comment]
Thanks for the link - I didn't know about this possibility!
Best regards,
Thomas

**Comment by hakan42** [comment]
Pull Request #17 is available.
