### ISSUE TITLE
Client Error: Not found for URL...

### ISSUE THREAD

**Issue by unicornis-pl** [buzz/ics2owncloud.py#8]
Greetings,

I am glad to see that my php code was useful ;-) 
(I posted it on the forum you referred to)

As my script is not good with new calendar app, I wanted to use your script. But I cannot get it running.

I get: 
`HTTPError: 404 Client Error: Not Found for url: https://cloud.domain.pl/remote.php/caldav/calendars/user/calendar_name?export`

When I changed the password to the wrong one in ini file the error message changed to: 
`HTTPError: 401 Client Error: Unauthorized for url: https:....`
so there is a connection to the server.
I checked both with /dav/ and /caldav/ in url, same result.
I am on OC 9.0.2 with Calendar app 1.2.2. OC server in behind the Apache proxy, but it should be transparent.

Any hints?

**Comment by buzz** [comment]
You get a 404. So obviously you got the wrong URL. You can check the correct one in the calendar app: _Settings_ in the bottom-left corner, then look for _Primary CalDAV address_.

**Comment by unicornis-pl** [comment]
Indeed, it was an URL problem. Calendar name in OC was in CAPITAL LETTERS but in url it was converted to lower case. Thank you.
