### ISSUE TITLE
Script fails when UID is an URL

### ISSUE THREAD

**Issue by unicornis-pl** [buzz/ics2owncloud.py#9]
I have exported my outlook calendar. One of the events is defined in ics as follows (see UID, bolded part):
BEGIN:VEVENT
**UID:https://www.domain.com/webcast/11111/22222**
SUMMARY:Zajęty
DTSTART;TZID=Central Europe Standard Time:20160712T140000
DTEND;TZID=Central Europe Standard Time:20160712T150000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20160713T171942Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:1467877786
X-MICROSOFT-CDO-APPT-SEQUENCE:1467877786
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:0
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT
and triggers an error:
`HTTPError: 404 Client Error: Not Found for url: https://cloud.mydomain.pl/remote.php/caldav/calendars/user/calendar/https://www.domain.com/webcast/11111/22222.ics`

Calendar item in question was an invitation to the webinar, in outlook it looks like all others.
If I store the calendar into ics file and import it via OC GUI it works fine.

**Comment by unicornis-pl** [comment]
My workaround:
_# import webcal
  imported_uids = []
  for e in c.walk('VEVENT'):
    uid = e['UID'].to_ical()**.translate(None,".:/")**
    cal = Calendar()
    cal.add_component(e)
    r = requests.put('%s/%s.ics' % (base_url, uid),
                     data=cal.to_ical(),
                     auth=(username, password),
                     headers={'content-type':'text/calendar; charset=UTF-8'}
                     )_
This converts url (https://www.domain.com/webcast/11111/22222) into plain string (httpswwwdomaincomwebcast1111122222)and now everything works.

**Comment by buzz** [comment]
cool
